name = "worker-rs-alarm"
main = "build/worker/shim.mjs"
compatibility_date = "2025-01-29"
compatibility_flags = ["durable_object_alarms"]

[build]
command = "worker-build --release"

[durable_objects]
bindings = [{ name = "Duo", class_name = "AlarmWKRS" }]

[[migrations]]
tag = "v1"
new_classes = ["AlarmWKRS"]

[triggers]
crons = ["* * * * *"]

[vars]
INTERNAL_HOST = "http://localhost:8877"
